# Generated by Django 3.2.6 on 2021-08-22 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursework', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='uid',
            new_name='user_token',
        ),
        migrations.RenameField(
            model_name='pool',
            old_name='pid',
            new_name='pool_id',
        ),
    ]
