# Generated by Django 3.2.6 on 2021-08-22 16:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coursework', '0002_auto_20210822_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='id',
            field=models.AutoField(auto_created=True, default=django.utils.timezone.now, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='user_token',
            field=models.CharField(default=None, editable=False, max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='pool',
            name='pool_id',
            field=models.CharField(default=None, editable=False, max_length=6, unique=True),
        ),
    ]
