# Generated by Django 3.2.6 on 2021-09-11 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coursework', '0004_rename_pool_id_pool_pool_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pool',
            name='group',
        ),
        migrations.CreateModel(
            name='ClientPoolLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='coursework.client')),
                ('pool', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='coursework.pool')),
            ],
        ),
    ]
