# Generated by Django 3.2.6 on 2021-09-12 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursework', '0006_auto_20210911_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='sum',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=42),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='comment',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
