# Generated by Django 3.2.6 on 2021-09-22 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursework', '0009_auto_20210921_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='closed_time',
        ),
        migrations.AddField(
            model_name='payment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
