# Generated by Django 3.2.6 on 2021-09-22 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursework', '0010_auto_20210922_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='closed_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
